/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-120257-gd9efdecc2b-g35a6de137a+2"
#endif /* AVUTIL_FFVERSION_H */
