/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-120904-gd94e2cf633-g1069d457c6+3"
#endif /* AVUTIL_FFVERSION_H */
