/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119136-g2f36ddc77e-20250403"
#endif /* AVUTIL_FFVERSION_H */
