/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-120733-g5a95246071-gcdbb5f1b93+3"
#endif /* AVUTIL_FFVERSION_H */
