/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119155-g3f30ae823e-20250406"
#endif /* AVUTIL_FFVERSION_H */
