/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119156-gc7adae928c-20250406"
#endif /* AVUTIL_FFVERSION_H */
