/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119165-gf3f1a48a07-20250407"
#endif /* AVUTIL_FFVERSION_H */
