/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119135-g1722f08acf-20250403"
#endif /* AVUTIL_FFVERSION_H */
