/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119167-gc368fca61f-20250407"
#endif /* AVUTIL_FFVERSION_H */
